import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,GoogleAuthProvider,signOut,sendPasswordResetEmail,sendEmailVerification}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,updateDoc,deleteDoc,addDoc,collection,query,where,onSnapshot,increment,deleteField}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import cfg from"./firebase-config.js";
const sec=initializeApp(cfg,'sec'),secAuth=getAuth(sec),app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={me:null,users:[],reqs:[],msgs:[],notifs:[],rats:[],grades:[],chats:[],view:'',chat:null,q:'',cm:0,ready:false},AV=['carlos','laura','jorge','valentina','ana'];
const DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const MENU={student:[['home','Inicio'],['mentors','Explorar mentores'],['profile','Mi perfil'],['mine','Mis mentorías'],['meet','Clases en Meet'],['chat','Mis conversaciones'],['notif','Notificaciones']],
mentor:[['home','Inicio'],['profile','Mi perfil'],['reqs','Solicitudes'],['chat','Mis conversaciones'],['cal','Mi cronograma'],['avail','Disponibilidad']],
admin:[['dash','Dashboard'],['students','Estudiantes'],['mentors','Mentores'],['mentorias','Mentorías'],['reqs','Solicitudes'],['msgs','Mensajes/Conexiones'],['reports','Reportes'],['profile','Mi perfil'],['cfg','Configuración']]};
const ini=u=>(u.name||'?').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const av=(u,s=40)=>u&&u.photo?`<img class=av src="${esc(u.photo)}" style="width:${s}px;height:${s}px" alt="">`:`<span class=av style="width:${s}px;height:${s}px">${ini(u||{})}</span>`;
const U=id=>S.users.find(u=>u.id===id)||{name:'Usuario eliminado'};
const toast=(t,e)=>{const d=document.createElement('div');d.textContent=t;if(e)d.className='e';$('#toast').append(d);setTimeout(()=>d.remove(),3500)};
const modal=h=>{const m=$('#modal');m.innerHTML=`<div>${h}</div>`;m.hidden=false};const close=()=>$('#modal').hidden=true;
const ERR={'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/email-already-in-use':'Ese correo ya está registrado.','auth/weak-password':'La contraseña debe tener al menos 6 caracteres.','auth/invalid-email':'El correo electrónico no es válido.','auth/network-request-failed':'Error de conexión.','auth/operation-not-allowed':'Activa el método Google en Firebase > Authentication > Método de acceso.','auth/unauthorized-domain':'Este dominio no está autorizado: agrégalo en Firebase > Authentication > Configuración > Dominios autorizados.','auth/popup-blocked':'El navegador bloqueó la ventana de Google. Permite ventanas emergentes.','auth/popup-closed-by-user':'Cerraste la ventana de Google antes de terminar.','auth/cancelled-popup-request':'Se canceló la ventana de Google. Inténtalo de nuevo.','permission-denied':'No tienes permiso para esta acción.'};
const T=async f=>{try{await f()}catch(e){toast(ERR[e.code]||ERR[e.message]||'Error: '+(e.code||e.message),1)}};
const arr=s=>String(s||'').split(',').map(x=>x.trim()).filter(Boolean);
const chips=a=>(a||[]).map(x=>`<span class=chip>${esc(x)}</span>`).join('');
const fdate=d=>d?new Date(d+'T00:00').toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'}):'';
const ago=t=>new Date(t).toLocaleString('es',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const stB=s=>({PENDIENTE:'y',ACEPTADA:'g',RECHAZADA:'r',Confirmada:'g',Pendiente:'y',Finalizada:'',Cancelada:'r'}[s]??'');
const rating=id=>{const r=S.rats.filter(x=>x.mentor===id);return r.length?{v:(r.reduce((a,x)=>a+x.value,0)/r.length).toFixed(1),n:r.length}:null};
const stars=id=>{const r=rating(id);return r?`⭐ ${r.v} (${r.n})`:'Sin calificaciones'};
const availTxt=m=>(m.availability||[]).map(a=>`${a.d} ${a.a}–${a.b}`).join(' · ')||'Sin definir';
const mentors=()=>S.users.filter(u=>u.role==='mentor'&&u.active!==false);
const mine=()=>S.reqs.filter(r=>r.members.includes(S.me.id));
const acc=()=>mine().filter(r=>r.status==='ACEPTADA');
const notify=(to,text)=>addDoc(collection(db,'notifications'),{to,text,ts:Date.now(),read:false});
const pack=f=>new Promise((ok,no)=>{const fr=new FileReader();fr.onerror=()=>no(new Error('No se pudo leer el archivo.'));
 if(f.type.startsWith('image/')){fr.onload=()=>{const i=new Image();i.onload=()=>{const k=Math.min(1,1280/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);const d=c.toDataURL('image/jpeg',.78);d.length>900000?no(new Error('La imagen es demasiado grande.')):ok({name:f.name,type:'image/jpeg',data:d})};i.onerror=()=>no(new Error('Imagen no válida.'));i.src=fr.result};fr.readAsDataURL(f)}
 else{if(f.size>650000)return no(new Error('El archivo supera 650 KB.'));fr.onload=()=>ok({name:f.name,type:f.type,data:fr.result});fr.readAsDataURL(f)}});
const cid=(a,b)=>[a,b].sort().join('_');
const wave=t=>`<span class=wave>${String(t).split(' ').map((w,k)=>`<span class=w>${[...w].map((c,i)=>`<i style="animation-delay:${(k*5+i)*.07}s">${esc(c)}</i>`).join('')}</span>`).join(' ')}</span>`;
const TY=['Clases en vivo por Google Meet','Mentores de todas las áreas','Avanza a tu ritmo y mide tu progreso','Aprende, comparte y crece en comunidad'];let ti=0,tc=0,tw=0,tdel=false;
setInterval(()=>{const e=document.querySelector('.typed');if(!e)return;const p=TY[ti];if(tw>0)tw--;else if(!tdel){tc++;if(tc>=p.length){tdel=true;tw=22}}else{tc--;if(tc<=0){tdel=false;ti=(ti+1)%TY.length}}e.textContent=p.slice(0,Math.max(tc,0))},80);
const ill=()=>`<svg class=ill viewBox="0 0 400 280" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="gg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#60a5fa"/><stop offset="1" stop-color="#a78bfa"/></linearGradient></defs><rect x="50" y="40" width="300" height="188" rx="16" fill="#fff" opacity=".96"/><rect x="62" y="52" width="276" height="160" rx="10" fill="url(#gg)"/><circle cx="140" cy="110" r="24" fill="#fff"/><rect x="108" y="138" width="64" height="58" rx="24" fill="#fff"/><circle cx="260" cy="110" r="24" fill="#fde68a"/><rect x="228" y="138" width="64" height="58" rx="24" fill="#fde68a"/><rect x="20" y="236" width="360" height="14" rx="7" fill="#fff" opacity=".9"/><g class="fl"><polygon points="200,6 250,26 200,46 150,26" fill="#0b1b4d"/><path d="M175 36v14c0 8 50 8 50 0V36l-25 10z" fill="#1e3a8a"/><rect x="246" y="26" width="3" height="22" fill="#d4a537"/></g><g class="fl2"><rect x="338" y="70" width="52" height="38" rx="12" fill="#fff"/><circle cx="352" cy="89" r="3" fill="#2563eb"/><circle cx="364" cy="89" r="3" fill="#2563eb"/><circle cx="376" cy="89" r="3" fill="#2563eb"/></g><g class="fl2"><rect x="8" y="120" width="56" height="40" rx="12" fill="#fde68a"/><text x="36" y="148" font-size="22" text-anchor="middle">⭐</text></g><g class="fl"><rect x="300" y="170" width="60" height="26" rx="13" fill="#16a34a"/><text x="330" y="188" font-size="12" fill="#fff" text-anchor="middle" font-family="Inter,sans-serif" font-weight="700">En vivo</text></g></svg>`;
const wd=d=>DAYS[(new Date(d+'T00:00').getDay()+6)%7];
const resv=()=>mine().filter(r=>r.mentor===S.me.id&&['PENDIENTE','ACEPTADA'].includes(r.status)&&(r.sesion||'')!=='Cancelada').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const MAXG=20;
const gradeOf=id=>{const g=S.grades.filter(x=>x.student===id);return g.length?{v:(g.reduce((a,x)=>a+(+x.value||0),0)/g.length).toFixed(1),n:g.length}:null};
const myGrade=sid=>S.grades.find(x=>x.student===sid&&x.mentor===S.me.id);
const fstu=()=>S.users.filter(u=>u.role==='student'&&u.active!==false).map(u=>({u,g:gradeOf(u.id)})).filter(x=>x.g).sort((a,b)=>b.g.v-a.g.v||b.g.n-a.g.n).slice(0,4).map(({u,g},i)=>`<div class=card><div class=row><span class=medal>${['🥇','🥈','🥉','⭐'][i]}</span>${av(u,48)}<div><b>${esc(u.name)}</b><br><small>${esc(u.career||'')} · ${esc(u.level||'')}</small></div></div><p><small>Nota promedio <b>${g.v}</b>/${MAXG} · ${g.n} calificación(es) de mentores</small></p><div class=bar><div style="width:${Math.min(100,g.v/MAXG*100)}%"></div></div><div>${chips(u.skills)}</div><div class=row style="margin-top:10px"><button class=btn data-a=pviewx data-id=${u.id}>Ver perfil</button><button class=btn data-a=msg data-id=${u.id}>💬 Mensaje</button>${S.me.role==='mentor'?`<button class="btn p" data-a=grade data-id=${u.id}>⭐ Calificar</button>`:''}</div></div>`).join('')||'<p class=sub>Aún no hay alumnos calificados por los mentores.</p>';
const reqTabs=()=>`<div class=row style="margin-bottom:12px">${[['','Todas'],['PENDIENTE','Pendientes'],['ACEPTADA','Aceptadas'],['RECHAZADA','Rechazadas']].map(([k,l])=>`<button class="btn ${(S.rf||'')===k?'p':''}" data-a=rf data-v="${k}">${l} (${k?mine().filter(r=>r.status===k).length:mine().length})</button>`).join('')}</div>`;
const rcell=(r,who)=>{const ss=r.sesion||'Confirmada';let h='';if(who==='m'&&r.status==='PENDIENTE')h+=`<button class="btn g" data-a=acc data-id=${r.id}>Aceptar</button> <button class="btn d" data-a=rej data-id=${r.id}>Rechazar</button>`;
 if(r.status==='ACEPTADA'){if(/^https:\/\//.test(r.meetLink||''))h+=`<a class="btn g" target=_blank rel=noopener href="${esc(r.meetLink)}">🎥 Unirme a Meet</a> `;if(who==='m'){h+=`<button class=btn data-a=meet data-id=${r.id}>🎥 ${r.meetLink?'Cambiar':'Añadir'} enlace Meet</button> `;if(ss==='Confirmada')h+=`<button class="btn ${r.live?'d':''}" data-a=live data-id=${r.id}>${r.live?'⏹ Terminar clase en vivo':'🔴 Iniciar clase en vivo'}</button> `;h+=`<button class=btn data-a=grade data-id=${r.student}>⭐ Calificar alumno</button>`}
  if(who==='s'&&ss==='Confirmada')h+=`<button class="btn d" data-a=ses data-s=Cancelada data-id=${r.id}>Cancelar</button>`;
  if(who==='s'&&ss==='Finalizada'&&!S.rats.some(x=>x.id===r.id))h+=`<select data-in=rate data-id=${r.id}><option value="">Calificar</option>${[5,4,3,2,1].map(v=>`<option>${v}</option>`).join('')}</select>`}return h};
let subs=[];
/* ---------- AUTH ---------- */
onAuthStateChanged(auth,async u=>{subs.forEach(f=>f());subs=[];S.ready=false;Object.assign(S,{users:[],reqs:[],msgs:[],notifs:[],rats:[],grades:[],chats:[],chat:null,view:'',q:'',fd:'',fe:0});
 if(!u){S.me=null;return render()}
 await T(async()=>{let d=await getDoc(doc(db,'users',u.uid));
  if(!d.exists()){const isA=(cfg.adminEmails||[]).includes(u.email);if(isA&&!u.emailVerified){await sendEmailVerification(u);toast('Te enviamos un correo de verificación. Verifícalo y vuelve a iniciar sesión.',1);S.pending=null;return signOut(auth)}if(!S.pending&&isA)S.pending={name:'',role:'student'};if(!S.pending){toast('Tu cuenta fue eliminada o no está registrada.',1);return signOut(auth)}
   await setDoc(doc(db,'users',u.uid),{...S.pending,role:(cfg.adminEmails||[]).includes(u.email)&&u.emailVerified?'admin':S.pending.role,name:S.pending.name||u.displayName||u.email,email:u.email,photo:u.photoURL||'',active:true,created:Date.now(),skills:[],availability:[],studentsCount:0});S.pending=null;d=await getDoc(doc(db,'users',u.uid))}
  if(d.data().active===false){toast('Tu cuenta está desactivada. Contacta al administrador.',1);return signOut(auth)}
  S.me={id:u.uid,...d.data()};if(!S.me.name){S.me.name=u.displayName||u.email;await updateDoc(doc(db,'users',u.uid),{name:S.me.name})}S.view='';listen();render()});if(!S.me)render()});
function listen(){const ad=S.me.role==='admin',id=S.me.id,M=c=>ad?collection(db,c):query(collection(db,c),where('members','array-contains',id)),
 on=(q,k,first)=>subs.push(onSnapshot(q,s=>{S[k]=s.docs.map(d=>({id:d.id,...d.data()}));if(first){S.ready=true;const m=S.users.find(x=>x.id===id);if(m){if(m.active===false)return signOut(auth);S.me=m}}refresh()},e=>{if(first){S.ready=true;refresh()}toast('Error de base de datos ('+(e.code||e.message)+'). Revisa que Firestore esté creado y las reglas publicadas.',1)}));
 on(collection(db,'users'),'users',1);on(M('requests'),'reqs');if(!ad)on(M('messages'),'msgs');if(ad)on(collection(db,'chats'),'chats');on(ad?collection(db,'notifications'):query(collection(db,'notifications'),where('to','==',id)),'notifs');on(collection(db,'ratings'),'rats');on(collection(db,'grades'),'grades')}
/* ---------- RENDER ---------- */
function refresh(){if(S.me&&S.view==='chat'&&$('#msgs')){$('#msgs').innerHTML=msgsHtml();$('#msgs').scrollTop=1e9;$('#cts').innerHTML=ctsHtml()}else render()}
function render(){const A=$('#app');if(!S.me)return A.innerHTML=landing();
 if(!S.ready)return A.innerHTML='<p style="padding:40px">Cargando datos…</p>';
 const m=MENU[S.me.role];if(!m.some(x=>x[0]===S.view))S.view=m[0][0];const un=S.notifs.filter(n=>!n.read&&n.to===S.me.id).length;
 A.innerHTML=`<div class=shell id=sh><aside><div class=logo><i>🎓</i>MentorApp</div>${m.map(x=>`<a class="${x[0]===S.view?'on':''}" data-a=go data-v=${x[0]}>${x[1]}${x[0]==='notif'&&un?` (${un})`:''}</a>`).join('')}<div class=me>${av(S.me,34)}<div>${esc(S.me.name)}<small>${{admin:'Administrador',mentor:'Mentor',student:'Estudiante'}[S.me.role]}</small></div></div><button class=btn data-a=out>Cerrar sesión</button></aside>
 <main><header><button class="btn burger" data-a=burger>☰</button><b>${m.find(x=>x[0]===S.view)[1]}</b><span class=sp></span><span>${esc(S.me.name)}</span>${av(S.me,34)}</header><section>${(V[S.me.role+'_'+S.view]||(()=>''))()}</section></main></div>`}
const landing=()=>`<div class=land><div class=in><div class="row sp"><div class=logo><i>🎓</i>MentorApp</div></div>
<div class="grid g2" style="align-items:center;margin-top:30px"><div><span class=badge style="background:#ffffff22;color:#fde68a">🎓 Mentorías universitarias</span><h1 style="font-size:40px;margin-top:12px">${wave('Conecta, aprende y crece')} <span class=shine>con el mentor adecuado</span></h1><p class=ty><span class=typed></span></p><p>MentorApp es la plataforma de mentorías para la comunidad universitaria: encuentra mentores académicos y profesionales, solicita sesiones, conversa y organiza tu cronograma de estudio.</p><div class=ill-wrap>${ill()}</div><div class=faces>${AV.map((a,i)=>`<img class=av src="avatars/${a}.jpg" alt="" style="width:46px;height:46px;animation-delay:${i*.3}s">`).join('')}<span>Únete a nuestra comunidad</span></div></div>
<div class="card auth" id=authbox>${authForm('login')}</div></div>
<h2 style="margin-top:44px">Áreas académicas</h2><div class="grid g4" style="margin-top:14px">${[['💻','Ingeniería y Tecnología'],['🧪','Ciencias'],['📊','Negocios y Economía'],['⚕️','Salud'],['⚖️','Derecho y Humanidades'],['🎨','Arte y Diseño']].map(x=>`<div class=card><h3><span class=ico>${x[0]}</span> ${x[1]}</h3></div>`).join('')}</div><h2 style="margin-top:44px">¿Cómo funciona?</h2><div class="grid g4" style="margin-top:14px">${[['1. Crea tu cuenta','Regístrate como estudiante o mentor.'],['2. Encuentra','Explora perfiles por especialidad, experiencia y disponibilidad.'],['3. Solicita','Envía tu solicitud y el mentor la acepta o rechaza.'],['4. Aprende','Conversa por chat y agenda tus sesiones.']].map(x=>`<div class=card><h3>${x[0]}</h3><p class=sub>${x[1]}</p></div>`).join('')}</div>
<h2 style="margin-top:40px">Beneficios</h2><div class="grid g4" style="margin-top:14px">${['Mentores verificados por el administrador','Chat con historial guardado','Contacto directo por WhatsApp','Cronograma de sesiones'].map(x=>`<div class=card>✅ ${x}</div>`).join('')}</div><footer class=f>© 2026 MentorApp · Plataforma de mentorías académicas y profesionales</footer></div></div>`;
const authForm=k=>`<h2>${k==='login'?'Iniciar sesión':k==='reg'?'Crear cuenta':'Recuperar contraseña'}</h2><form data-f=${k}>${k==='reg'?'<label>Nombre completo</label><input name=name>':''}<label>Correo electrónico</label><input name=email type=email>${k!=='rec'?'<label>Contraseña</label><input name=pass type=password>':''}${k!=='login'&&k!=='rec'?'<label>Confirmar contraseña</label><input name=pass2 type=password>':''}
${k!=='rec'?'<label>Soy (cuentas nuevas)</label><select name=role><option value=student>Estudiante</option><option value=mentor>Mentor</option></select>':''}<button class="btn p" style="width:100%">${k==='login'?'Iniciar sesión':k==='reg'?'Crear cuenta':'Enviar enlace'}</button></form>
${k!=='rec'?'<button class=btn style="width:100%;margin-top:8px" data-a=google>Entrar con Google</button>':''}<p class=row style="font-size:13px">${k==='login'?'<a href=# data-a=af data-k=reg>Crear cuenta</a> · <a href=# data-a=af data-k=rec>¿Olvidaste tu contraseña?</a>':'<a href=# data-a=af data-k=login>Volver a iniciar sesión</a>'}</p>`;
/* ---------- COMPONENTES ---------- */
const mcard=m=>`<div class=card><div class=row>${av(m,52)}<div><b>${esc(m.name)}</b><br><span class=sub>${esc(m.specialty||'Mentor')}</span></div></div><p>${stars(m.id)} · ${esc(m.experience||0)} años exp.</p><div>${chips(m.skills)}</div><small>🕒 ${esc(availTxt(m))}</small><div class=row style="margin-top:10px"><button class=btn data-a=mview data-id=${m.id}>Ver perfil</button><button class="btn p" data-a=mreq data-id=${m.id}>Solicitar mentoría</button><button class=btn data-a=msg data-id=${m.id}>💬</button></div></div>`;
const mfilter=()=>{const q=S.q.toLowerCase(),d=S.fd||'',e=+(S.fe||0);return mentors().filter(m=>(!q||[m.name,m.specialty,...(m.skills||[])].join(' ').toLowerCase().includes(q))&&(!d||(m.availability||[]).some(a=>a.d===d))&&(+m.experience||0)>=e)};
const mlist=()=>mfilter().map(mcard).join('')||'<p class=sub>No se encontraron mentores.</p>';
const filters=()=>`<div class="card row" style="margin-bottom:16px"><input style="flex:2;margin:0" id=q placeholder="Buscar por nombre, especialidad o habilidad" value="${esc(S.q)}" data-in=mq><select style="flex:1;margin:0" data-in=fd><option value="">Cualquier día</option>${DAYS.map(d=>`<option ${S.fd===d?'selected':''}>${d}</option>`).join('')}</select><select style="flex:1;margin:0" data-in=fe>${[0,1,3,5,10].map(n=>`<option value=${n} ${+S.fe===n?'selected':''}>${n}+ años exp.</option>`).join('')}</select></div>`;
const wa=m=>m.whatsapp?`<a class="btn g" target=_blank rel=noopener href="https://wa.me/${esc(m.whatsapp.replace(/\D/g,''))}">Contactar por WhatsApp</a>`:'';
const field=(n,l,v='',t='text')=>`<label>${l}</label><input name=${n} type=${t} value="${esc(v)}">`;
const pform=(u,adm)=>{const m=u.role==='mentor',s=u.role==='student',a=u.role==='admin',j=x=>(x||[]).join(', ');return `<h2 style="margin-bottom:10px">Editar perfil</h2><form data-f=prof data-id=${u.id}>${field('name','Nombre completo',u.name)}${field('city','Ciudad y país',u.city)}${a?'':field('institution',m?'Empresa o institución':'Universidad o institución',u.institution)+field('faculty','Facultad / área académica',u.faculty)}
<label>Acerca de mí</label><textarea name=bio rows=3>${esc(u.bio)}</textarea>
${m?field('specialty','Especialidad',u.specialty)+field('experience','Años de experiencia',u.experience,'number')+field('studies','Estudios',u.studies)+field('skills','Habilidades (separadas por coma)',j(u.skills))+field('courses','Cursos (separados por coma)',j(u.courses))+field('whatsapp','WhatsApp (con código de país, ej. 51987654321)',u.whatsapp):''}
${s?field('career','Carrera',u.career)+field('level','Nivel (ej. 5to ciclo)',u.level)+field('skills','Habilidades (coma)',j(u.skills))+field('interests','Áreas de interés (coma)',j(u.interests)):''}
${a?'':field('languages','Idiomas (coma)',j(u.languages))+field('linkedin','LinkedIn (URL)',u.linkedin)}
<label>Foto (URL o elige una)</label><input name=photo id=ph value="${esc(u.photo)}" list=pl><datalist id=pl>${AV.map(a=>`<option value="avatars/${a}.jpg">`).join('')}</datalist><div class=row style="margin-bottom:10px">${AV.map(a=>`<img class=av data-a=pick data-p="avatars/${a}.jpg" src="avatars/${a}.jpg" style="width:40px;height:40px;cursor:pointer">`).join('')}</div>
<div class=row><button class="btn p">Guardar cambios</button><button type=button class=btn data-a=close>Cancelar</button></div></form>`};
const chipEd=(u,k,l)=>{const own=u.id===S.me.id&&u.role!=='admin',a=u[k]||[];return (a.length||own)?`<h3 style="margin-top:14px">${l}</h3><div>${a.map((x,i)=>`<span class=chip>${esc(x)}${own?` <a data-a=idel data-k=${k} data-i=${i} style="cursor:pointer" title=Quitar>✕</a>`:''}</span>`).join('')||'<small>Aún no agregaste ninguno.</small>'}</div>${own?`<form data-f=iadd data-k=${k} class=row style="flex-wrap:nowrap;margin-top:6px"><input name=v placeholder="Agregar (separa con comas)" style="margin:0"><button class="btn p">Agregar</button></form>`:''}`:''};
const kv=(l,v)=>v?`<b>${l}</b><span>${v}</span>`:'';
const pview=u=>{const m=u.role==='mentor',s=u.role==='student',own=u.id===S.me.id,ks=m?['specialty','bio','experience','studies','city','institution','whatsapp','photo']:s?['career','level','bio','city','institution','photo']:['bio','city','photo'],pc=Math.round((ks.filter(k=>u[k]).length+((u.skills||[]).length?1:0))/(ks.length+1)*100),r=m&&rating(u.id),
 head=(m?[u.specialty,u.institution]:s?[u.career,u.level]:['Administrador de la plataforma']).filter(Boolean).map(esc).join(' · '),
 st=m?[['Estudiantes',+u.studentsCount||0],['Calificación',r?r.v+' ⭐':'—'],['Experiencia',(u.experience||0)+' años']]:s?[['Nota promedio',gradeOf(u.id)?gradeOf(u.id).v+'/'+MAXG:'—'],['Habilidades',(u.skills||[]).length],['Intereses',(u.interests||[]).length]]:[['Estudiantes',S.users.filter(x=>x.role==='student').length],['Mentores',S.users.filter(x=>x.role==='mentor').length],['Pendientes',S.reqs.filter(x=>x.status==='PENDIENTE').length]];
 return `<div class=card style="padding:0;overflow:hidden"><div class=cover></div><div style="padding:0 24px 24px"><div class="row sp" style="margin-top:-48px;align-items:flex-end"><span class=pav>${av(u,96)}</span>${own?'<div class=row><button class="btn p" data-a=pedit>Editar perfil</button>'+(u.role!=='admin'?'<button class=btn data-a=reset>🔑 Cambiar contraseña</button>':'')+'</div>':''}</div>
 <h2 style="margin-top:10px">${esc(u.name)} <span class=badge>${{admin:'Administrador',mentor:'Mentor',student:'Estudiante'}[u.role]}</span></h2><p class=sub style="margin:4px 0 8px">${head}</p><p class=sub>${u.city?'📍 '+esc(u.city):''}</p>
 <div class="grid g4" style="margin:14px 0">${st.map(x=>`<div class="card stat" style="box-shadow:none;border:1px solid #eef1f9"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 ${own&&!(u.role==='admin')?`<small>Perfil completo al ${pc}%</small><div class=bar><div style="width:${pc}%"></div></div>`:''}</div></div>
 <div class="grid g2" style="margin-top:16px"><div class=card><h3>Acerca de</h3><p>${esc(u.bio||'Aún no hay información.')}</p>${chipEd(u,'skills','Habilidades')}${chipEd(u,'interests','Áreas de interés')}</div>
 <div class=card><h3>Información</h3><div class=kv>${kv('Correo',esc(u.email))}${kv('Institución',esc(u.institution))}${kv('Facultad',esc(u.faculty))}${kv('Idiomas',esc((u.languages||[]).join(', ')))}${kv('LinkedIn',/^https?:/.test(u.linkedin||'')?`<a href="${esc(u.linkedin)}" target=_blank rel=noopener>Ver perfil</a>`:'')}${m?kv('Estudios',esc(u.studies))+kv('Cursos',esc((u.courses||[]).join(', ')))+kv('WhatsApp',esc(u.whatsapp)):''}${s?kv('Carrera',esc(u.career))+kv('Nivel',esc(u.level)):''}</div>${m&&u.whatsapp?`<p>${wa(u)}</p>`:''}</div>
 ${m?`<div class=card><h3>Disponibilidad</h3>${(u.availability||[]).map(a=>`<div class="row sp"><span>${a.d}</span><b>${a.a} – ${a.b}</b></div>`).join('')||'<p class=sub>Sin definir.</p>'}</div>`:''}</div>`};
const reqRow=(r,who)=>{const o=U(who==='m'?r.student:r.mentor);return `<tr><td><div class=row>${av(o,36)}<div><b>${esc(o.name)}</b><br><small>${esc(o.career||o.specialty||'')} ${esc(o.level||'')}</small></div></div></td><td>${esc(r.specialty)}</td><td>${esc(r.message)}</td><td>${fdate(r.date)} ${esc(r.time)}</td><td><span class="badge ${stB(r.status)}">${r.status}</span>${r.status==='ACEPTADA'?` <span class="badge ${stB(r.sesion||'Confirmada')}">${r.sesion||'Confirmada'}</span>`:''}</td><td>${rcell(r,who)}</td></tr>`};
const rtable=(rs,who)=>rs.length?`<div class="card tw"><table><tr><th>${who==='m'?'Estudiante':'Mentor'}</th><th>Especialidad</th><th>Mensaje</th><th>Fecha</th><th>Estado</th><th></th></tr>${rs.map(r=>reqRow(r,who)).join('')}</table></div>`:'<div class=card><p class=sub>No hay solicitudes todavía.</p></div>';
const ctsList=()=>{const h=S.me.hiddenChats||{};return [...new Set([...acc().map(r=>r.members.find(x=>x!==S.me.id)),...S.msgs.map(m=>m.members.find(x=>x!==S.me.id)),...(S.chat?[S.chat]:[])])].filter(Boolean).filter(id=>id===S.chat||!h[id]||S.msgs.some(m=>m.from===id&&m.ts>h[id]))};
const ctsHtml=()=>ctsList().map(id=>{const u=U(id);return `<div class="ct ${S.chat===id?'on':''}" data-a=open data-id=${id}>${av(u,36)}<b>${esc(u.name)}</b></div>`}).join('')||'<p class=sub>Aún no tienes conversaciones. Abre el perfil de un mentor o alumno y pulsa «Enviar mensaje».</p>';
const msgsHtml=()=>{if(!S.chat)return '<p class=sub>Selecciona una conversación.</p>';const id=cid(S.me.id,S.chat),l=S.msgs.filter(m=>m.chatId===id).sort((a,b)=>a.ts-b.ts);return l.map(m=>{const mi=m.from===S.me.id;const fl=m.file?(m.file.type.startsWith('image/')?`<a href="${esc(m.file.data)}" target=_blank><img src="${esc(m.file.data)}" style="max-width:100%;border-radius:8px;margin-top:4px"></a>`:`<br><a download="${esc(m.file.name)}" href="${esc(m.file.data)}" style="color:inherit">📄 ${esc(m.file.name)}</a>`):'';return `<div class="bub ${mi?'me2':''}"><small>${esc(U(m.from).name)} · ${ago(m.ts)}${mi?' ✓':''}</small>${esc(m.text)}${fl}</div>`}).join('')||'<p class=sub>Aún no hay mensajes. ¡Escribe el primero!</p>'};
const chatV=()=>{if(S.chat&&!ctsList().includes(S.chat))S.chat=null;const o=S.chat?U(S.chat):null;return `<div class=chat><div class=card id=cts style="overflow:auto">${ctsHtml()}</div><div class=card style="display:flex;flex-direction:column"><div class=row>${o?av(o,36)+`<b>${esc(o.name)}</b>${wa(o)}<button class="btn d" data-a=cdel style="margin-left:auto">Eliminar contacto</button>`:'<b>Conversación</b>'}</div><div class=msgs id=msgs>${msgsHtml()}</div>${S.chat?'<form data-f=msg class=row style="flex-wrap:nowrap"><label class=btn style="margin:0">📎<input type=file name=f data-in=file hidden accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip,.txt"></label><input name=t placeholder="Escribe un mensaje…" style="margin:0" autocomplete=off><button class="btn p">Enviar</button></form>':''}</div></div>`};
const calV=()=>{const d=new Date();d.setMonth(d.getMonth()+S.cm,1);const y=d.getFullYear(),mo=d.getMonth(),first=(d.getDay()+6)%7,n=new Date(y,mo+1,0).getDate(),ev=acc().filter(r=>r.sesion!=='Cancelada'),key=i=>`${y}-${String(mo+1).padStart(2,'0')}-${String(i).padStart(2,'0')}`;
 let c=DAYS.map(x=>`<b>${x.slice(0,3)}</b>`).join('')+'<div style="background:none"></div>'.repeat(first);for(let i=1;i<=n;i++)c+=`<div class="${ev.some(r=>r.date===key(i))?'ev':''}">${i}</div>`;
 const l=acc().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 return `<div class="grid g2"><div class=card><div class="row sp"><button class=btn data-a=cm data-d=-1>◀</button><b>${d.toLocaleDateString('es',{month:'long',year:'numeric'})}</b><button class=btn data-a=cm data-d=1>▶</button></div><div class=cal style="margin-top:12px">${c}</div></div>
 <div class="card tw"><h3>Sesiones</h3>${l.length?`<table>${l.map(r=>{const o=U(S.me.role==='mentor'?r.student:r.mentor),ss=r.sesion||'Confirmada';return `<tr><td>${fdate(r.date)} ${esc(r.time)}</td><td>${esc(o.name)}<br><small>${esc(r.specialty)}</small>${/^https:\/\//.test(r.meetLink||'')?`<br><a target=_blank rel=noopener href="${esc(r.meetLink)}">🎥 Entrar a Meet</a>`:''}${S.me.role==='mentor'&&ss==='Confirmada'?`<br><a href=# data-a=meet data-id=${r.id}>✏️ enlace Meet</a>`:''}</td><td><span class="badge ${stB(ss)}">${ss}</span></td><td>${ss==='Confirmada'?`${S.me.role==='mentor'?`<button class="btn g" data-a=ses data-s=Finalizada data-id=${r.id}>Finalizar</button> `:''}<button class="btn d" data-a=ses data-s=Cancelada data-id=${r.id}>Cancelar</button>`:ss==='Finalizada'&&S.me.role==='student'&&!S.rats.some(x=>x.id===r.id)?`<select data-in=rate data-id=${r.id}><option value="">Calificar</option>${[5,4,3,2,1].map(v=>`<option>${v}</option>`).join('')}</select>`:''}</td></tr>`}).join('')}</table>`:'<p class=sub>No tienes sesiones programadas.</p>'}</div></div>`};
const stat=(l,v)=>`<div class="card stat"><span>${l}</span><b>${v}</b></div>`;
const peopleTable=(rows,adm)=>`<div class="card tw"><table><tr><th>Usuario</th><th>Correo</th><th>Detalle</th><th>Estado</th><th></th></tr>${rows.map(u=>`<tr><td><div class=row>${av(u,34)}${esc(u.name)}</div></td><td>${esc(u.email)}</td><td>${esc(u.specialty||u.career||'')}</td><td><span class="badge ${u.active===false?'r':'g'}">${u.active===false?'Inactivo':'Activo'}</span></td><td><button class=btn data-a=uedit data-id=${u.id}>Ver perfil</button> <button class=btn data-a=utog data-id=${u.id}>${u.active===false?'Activar':'Desactivar'}</button> <button class="btn d" data-a=udel data-id=${u.id}>Eliminar</button></td></tr>`).join('')||'<tr><td>Sin resultados</td></tr>'}</table></div>`;
const sbox=()=>`<input placeholder="Buscar…" value="${esc(S.q)}" data-in=sq>`;
const myStudents=()=>acc().map(r=>({r,u:U(r.student)}));
/* ---------- VISTAS ---------- */
const V={
student_home:()=>`<div class=hero><div class=hbg>${ill()}</div><h1>${wave('¡Hola, '+S.me.name.split(' ')[0]+'!')}</h1><p>Encuentra el mentor ideal para ti</p><p class=ty><span class=typed></span></p><div class=row><input id=hq placeholder="Buscar mentores por especialidad, nombre o área…" style="max-width:420px"><button class="btn p" data-a=hsearch>Buscar</button></div></div><h3 style="margin:20px 0 10px">Mentores destacados</h3><div class="grid g4">${[...mentors()].sort((a,b)=>(rating(b.id)?.v||0)-(rating(a.id)?.v||0)).slice(0,4).map(mcard).join('')||'<p class=sub>Aún no hay mentores registrados.</p>'}</div><h3 style="margin:20px 0 10px">Mis próximas mentorías</h3>${acc().slice(0,3).map(r=>`<div class=card>${esc(U(r.mentor).name)} · ${esc(r.specialty)} · ${fdate(r.date)} ${esc(r.time)}</div>`).join('')||'<p class=sub>Sin mentorías aceptadas.</p>'}<h3 style="margin:20px 0 10px">🏆 Alumnos destacados · mejores notas de los mentores</h3><div class="grid g4">${fstu()}</div>`,
student_mentors:()=>filters()+`<div class="grid g4" id=list>${mlist()}</div>`,
student_profile:()=>pview(S.me),
student_meet:()=>{const ses=acc().filter(r=>(r.sesion||'Confirmada')==='Confirmada').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),live=ses.filter(r=>r.live);
 const link=r=>/^https:\/\//.test(r.meetLink||'')?`<a class="btn g" target=_blank rel=noopener href="${esc(r.meetLink)}">🎥 Unirme a Meet</a>`:'<span class="badge y">Esperando enlace del mentor</span>';
 return `<div class="grid g2"><div class=card><h3>🔴 En clase ahora</h3>${live.map(r=>{const o=U(r.mentor);return `<div class="row sp" style="padding:8px 0"><div class=row>${av(o,40)}<div><b>${esc(o.name)}</b><br><small>${esc(r.specialty)} · en vivo con ${esc(S.me.name)}</small></div></div>${link(r)}</div>`}).join('')||'<p class=sub>Ningún mentor está en clase ahora. Cuando inicie tu clase, aparecerá aquí.</p>'}</div><div class=card><h3>📅 Mis próximas clases por Meet</h3>${ses.map(r=>{const o=U(r.mentor);return `<div class="row sp" style="padding:8px 0"><div class=row>${av(o,36)}<div><b>${esc(o.name)}</b><br><small>${fdate(r.date)} ${esc(r.time)} · ${esc(r.specialty)}</small></div></div>${link(r)}</div>`}).join('')||'<p class=sub>Aún no tienes clases confirmadas.</p>'}</div></div><h3 style="margin:20px 0 10px">Solicitar una clase por Meet</h3><div class="grid g4">${S.users.filter(u=>u.role==='mentor'&&u.active!==false).map(m=>`<div class=card><div class=row>${av(m,44)}<div><b>${esc(m.name)}</b><br><small>${esc(m.specialty||'Mentor')}</small></div></div><p><small>🕒 ${esc(availTxt(m))}</small></p><button class="btn p" data-a=mreq data-id=${m.id}>Solicitar clase</button></div>`).join('')||'<p class=sub>No hay mentores disponibles.</p>'}</div>`},
student_mine:()=>rtable(mine().sort((a,b)=>b.created-a.created),'s'),
student_chat:chatV,student_cal:calV,
student_peers:()=>`<div class="card row" style="margin-bottom:16px"><input id=q style="margin:0" placeholder="Filtrar por nombre, carrera, habilidad o interés" value="${esc(S.q)}" data-in=pq></div><div class="grid g4" id=list>${plist()}</div>`,
student_notif:()=>`<div class=card>${S.notifs.sort((a,b)=>b.ts-a.ts).map(n=>`<p class=row>${n.read?'':'🔵'} ${esc(n.text)} <small>${ago(n.ts)}</small></p>`).join('')||'<p class=sub>Sin notificaciones.</p>'}<button class=btn data-a=readall>Marcar todas como leídas</button></div>`,
mentor_home:()=>{const m=S.me,p=mine().filter(r=>r.status==='PENDIENTE');return `<div class=card><div class=row>${av(m,64)}<div><h2>${wave('Hola, '+m.name)}</h2><p class=sub>Comparte tu experiencia y ayuda a más personas a crecer.</p><p class=ty><span class=typed></span></p></div></div></div><div class="grid g4" style="margin:16px 0">${stat('Estudiantes',new Set(acc().map(r=>r.student)).size)}${stat('Mentorías activas',acc().filter(r=>(r.sesion||'Confirmada')==='Confirmada').length)}${stat('Solicitudes pendientes',p.length)}${stat('Calificación',rating(m.id)?.v||'—')}</div><div class="grid g2"><div class=card><h3>Próximas sesiones</h3>${acc().filter(r=>(r.sesion||'Confirmada')==='Confirmada').slice(0,4).map(r=>`<p>${esc(U(r.student).name)} · ${fdate(r.date)} ${esc(r.time)}</p>`).join('')||'<p class=sub>Sin sesiones.</p>'}</div><div class=card><h3>Mensajes recientes</h3>${[...S.msgs].sort((a,b)=>b.ts-a.ts).slice(0,4).map(x=>`<p><b>${esc(U(x.from).name)}</b>: ${esc(x.text)} <small>${ago(x.ts)}</small></p>`).join('')||'<p class=sub>Sin mensajes.</p>'}</div><div class=card><h3>Mis estudiantes aceptados</h3>${[...new Map(myStudents().map(x=>[x.u.id,x])).values()].map(({u})=>`<p class=row>${av(u,30)}<span>${esc(u.name)}<br><small>${esc(u.career||'')} · Mi nota: ${myGrade(u.id)?myGrade(u.id).value+'/'+MAXG:'sin calificar'}</small></span><button class=btn data-a=grade data-id=${u.id}>⭐ Calificar</button></p>`).join('')||'<p class=sub>Aún no aceptaste estudiantes.</p>'}</div></div><h3 style="margin:20px 0 10px">🏆 Alumnos destacados · mejores notas de los mentores</h3><div class="grid g4">${fstu()}</div>`},
mentor_profile:()=>pview(S.me),
mentor_reqs:()=>reqTabs()+rtable(mine().filter(r=>!S.rf||r.status===S.rf).sort((a,b)=>b.created-a.created),'m'),mentor_chat:chatV,mentor_cal:calV,
mentor_avail:()=>{const rs=resv(),ds=S.me.availability||[];
 return `<div class="grid g2"><div class=card><h3>🗓️ Mis horarios</h3><p class=sub>Marca los días en que atiendes y define la hora.</p><div class=row style="margin:8px 0"><button type=button class=btn data-a=avp data-p=wk>Lun–Vie</button><button type=button class=btn data-a=avp data-p=all>Todos</button><button type=button class=btn data-a=avp data-p=none>Ninguno</button></div><form data-f=avail>${DAYS.map(d=>{const a=ds.find(x=>x.d===d);return `<div class=row><label style="width:110px"><input type=checkbox name=on_${d} style="width:auto" ${a?'checked':''}> ${d}</label><input type=time name=a_${d} value="${a?.a||'18:00'}" style="width:130px"><input type=time name=b_${d} value="${a?.b||'21:00'}" style="width:130px"></div>`}).join('')}<button class="btn p">Guardar disponibilidad</button></form></div>
 <div class=card><h3>📌 Días disponibles y reservas</h3>${DAYS.map(d=>{const a=ds.find(x=>x.d===d),l=rs.filter(r=>wd(r.date)===d);return `<div class=dayrow><div class="row sp"><b>${d}</b>${a?`<span class="badge g">✔ Disponible ${a.a} – ${a.b}</span>`:'<span class=badge>No disponible</span>'}</div>${l.map(r=>{const o=U(r.student),dentro=a&&r.time>=a.a&&r.time<=a.b;return `<div class="row resv">${av(o,28)}<span><b>${esc(o.name)}</b> reservó el ${fdate(r.date)} a las <b>${esc(r.time)}</b> <span class="badge ${stB(r.status)}">${r.status}</span>${!a?' <span class="badge y">día no disponible</span>':!dentro?' <span class="badge y">fuera de horario</span>':''}</span></div>`}).join('')||(a?'<small>Sin reservas este día</small>':'')}</div>`}).join('')}</div></div>
 <div class="card tw" style="margin-top:16px"><h3>✅ Quiénes reservaron su cita</h3>${rs.length?`<table><tr><th>Estudiante</th><th>Día</th><th>Fecha</th><th>Hora reservada</th><th>Estado</th></tr>${rs.map(r=>{const o=U(r.student);return `<tr><td><div class=row>${av(o,32)}${esc(o.name)}</div></td><td>${wd(r.date)}</td><td>${fdate(r.date)}</td><td><b>${esc(r.time)}</b></td><td><span class="badge ${stB(r.status)}">${r.status}</span></td></tr>`}).join('')}</table>`:'<p class=sub>Todavía nadie reservó una cita contigo.</p>'}</div>`},
admin_dash:()=>{const st=S.users.filter(u=>u.role==='student'),mt=S.users.filter(u=>u.role==='mentor'),mo=[...Array(12)].map((_,i)=>[st,mt].map(l=>l.filter(u=>new Date(u.created).getMonth()===i&&new Date(u.created).getFullYear()===new Date().getFullYear()).length)),mx=Math.max(1,...mo.flat()),pt=k=>mo.map((v,i)=>`${20+i*50},${130-v[k]/mx*110}`).join(' ');
 return `<div class="grid g4">${stat('Total de estudiantes',st.length)}${stat('Total de mentores',mt.length)}${stat('Mentores activos',mt.filter(u=>u.active!==false).length)}${stat('Solicitudes pendientes',S.reqs.filter(r=>r.status==='PENDIENTE').length)}${stat('Mentorías activas',S.reqs.filter(r=>r.status==='ACEPTADA'&&(r.sesion||'Confirmada')==='Confirmada').length)}${stat('Mensajes / conexiones',S.chats.reduce((a,c)=>a+(c.count||0),0))}</div><div class="grid g2" style="margin-top:16px"><div class=card><h3>Registros por mes (este año)</h3><svg viewBox="0 0 600 150" width=100%><polyline fill=none stroke="#2563eb" stroke-width=3 points="${pt(0)}"/><polyline fill=none stroke="#7c3aed" stroke-width=3 points="${pt(1)}"/></svg><small><span style=color:#2563eb>● Estudiantes</span> <span style=color:#7c3aed>● Mentores</span> · Ene→Dic</small></div><div class=card><h3>Solicitudes recientes</h3>${[...S.reqs].sort((a,b)=>b.created-a.created).slice(0,5).map(r=>`<p>${esc(U(r.student).name)} → ${esc(U(r.mentor).name)} <span class="badge ${stB(r.status)}">${r.status}</span></p>`).join('')||'<p class=sub>Sin solicitudes.</p>'}</div><div class=card><h3>Usuarios recientes</h3>${[...S.users].sort((a,b)=>b.created-a.created).slice(0,5).map(u=>`<p class=row>${av(u,28)}${esc(u.name)} <span class=badge>${u.role}</span></p>`).join('')}</div><div class=card><h3>Últimas actividades</h3>${[...S.notifs].sort((a,b)=>b.ts-a.ts).slice(0,6).map(n=>`<p>${esc(n.text)} <small>${ago(n.ts)}</small></p>`).join('')||'<p class=sub>Sin actividad.</p>'}</div></div>`},
admin_students:()=>`<div class="row" style="margin-bottom:12px"><div style="flex:1">${sbox()}</div><button class="btn p" data-a=uadd data-r=student>+ Agregar estudiante</button></div><div id=list>${peopleTable(plain('student'))}</div>`,
admin_mentors:()=>`<div class="row" style="margin-bottom:12px"><div style="flex:1">${sbox()}</div><button class="btn p" data-a=uadd data-r=mentor>+ Agregar mentor</button></div><div id=list>${peopleTable(plain('mentor'))}</div>`,
admin_mentorias:()=>`<div style="margin-bottom:12px"><button class="btn p" data-a=mnew>+ Programar mentoría</button></div><div class="card tw"><table><tr><th></th><th>Mentor</th><th>Estudiante</th><th>Especialidad</th><th>Fecha</th><th>Hora</th><th>Estado</th></tr>${S.reqs.filter(r=>r.status==='ACEPTADA').map(r=>`<tr><td><button class="btn d" data-a=rdel data-id=${r.id}>Eliminar</button></td><td>${esc(U(r.mentor).name)}</td><td>${esc(U(r.student).name)}</td><td>${esc(r.specialty)}</td><td>${fdate(r.date)}</td><td>${esc(r.time)}</td><td><select data-in=ases data-id=${r.id}>${['Pendiente','Confirmada','Finalizada','Cancelada'].map(s=>`<option ${(r.sesion||'Confirmada')===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td>Sin mentorías.</td></tr>'}</table></div>`,
admin_reqs:()=>`<div class="card tw"><table><tr><th>Estudiante</th><th>Mentor</th><th>Especialidad</th><th>Fecha</th><th>Estado</th><th></th></tr>${S.reqs.map(r=>`<tr><td>${esc(U(r.student).name)}</td><td>${esc(U(r.mentor).name)}</td><td>${esc(r.specialty)}</td><td>${fdate(r.date)}</td><td><span class="badge ${stB(r.status)}">${r.status}</span></td><td>${r.status==='PENDIENTE'?`<button class="btn g" data-a=aacc data-id=${r.id}>Aceptar</button> <button class="btn d" data-a=arej data-id=${r.id}>Rechazar</button> `:''}<button class="btn d" data-a=rdel data-id=${r.id}>Eliminar</button></td></tr>`).join('')||'<tr><td>Sin solicitudes.</td></tr>'}</table></div>`,
admin_msgs:()=>`<p class=sub>🔒 Por privacidad, el administrador ve solo cuántas conversaciones y mensajes hay, no su contenido.</p><div class="card tw"><table><tr><th>Conexión</th><th>Mensajes</th><th>Último</th></tr>${S.chats.map(c=>`<tr><td>${esc(U(c.members[0]).name)} ↔ ${esc(U(c.members[1]).name)}</td><td>${c.count||0}</td><td>${ago(c.last)}</td></tr>`).join('')||'<tr><td>Sin conversaciones.</td></tr>'}</table></div>`,
admin_reports:()=>`<div class="grid g4">${['PENDIENTE','ACEPTADA','RECHAZADA'].map(s=>stat('Solicitudes '+s.toLowerCase()+'s',S.reqs.filter(r=>r.status===s).length)).join('')}${['Finalizada','Cancelada'].map(s=>stat('Mentorías '+s.toLowerCase()+'s',S.reqs.filter(r=>r.sesion===s).length)).join('')}${stat('Calificaciones',S.rats.length)}${stat('Usuarios inactivos',S.users.filter(u=>u.active===false).length)}</div>`,
admin_profile:()=>pview(S.me),admin_cfg:()=>`<div class=card><h3>Cuenta de administrador</h3><p>${esc(S.me.email)}</p><button class=btn data-a=reset>Enviar correo para cambiar contraseña</button></div>`};
V.mentor_peers=V.student_peers;
const plain=r=>S.users.filter(u=>u.role===r&&(!S.q||(u.name+u.email+(u.specialty||'')+(u.career||'')).toLowerCase().includes(S.q.toLowerCase())));
const plist=()=>S.users.filter(u=>u.role==='student'&&u.id!==S.me.id&&u.active!==false&&(!S.q||[u.name,u.career,...(u.skills||[]),...(u.interests||[])].join(' ').toLowerCase().includes(S.q.toLowerCase()))).map(u=>`<div class=card><div class=row>${av(u,48)}<div><b>${esc(u.name)}</b><br><small>${esc(u.career||'')} · ${esc(u.level||'')}</small></div></div><div>${chips(u.skills)}${chips(u.interests)}</div><small>Progreso ${+u.progress||0}%</small><div style="background:#e5e9f5;border-radius:9px;height:8px"><div style="width:${+u.progress||0}%;background:var(--b);height:8px;border-radius:9px"></div></div><div class=row style="margin-top:10px"><button class=btn data-a=pviewx data-id=${u.id}>Ver perfil</button><button class=btn data-a=msg data-id=${u.id}>💬 Mensaje</button></div></div>`).join('')||'<p class=sub>No hay alumnos para mostrar.</p>';
/* ---------- ACCIONES ---------- */
const mprofile=m=>pview(m)+`<div class=row style="margin-top:14px">${S.me.role==='student'&&m.role==='mentor'?`<button class="btn p" data-a=mreq data-id=${m.id}>Solicitar mentoría</button>`:''}${S.me.id!==m.id&&S.me.role!=='admin'?`<button class=btn data-a=msg data-id=${m.id}>💬 Enviar mensaje</button>`:''}<button class=btn data-a=close>Cerrar</button></div>`;
const upd=(id,d)=>T(async()=>{await updateDoc(doc(db,'users',id),d);toast('Cambios guardados correctamente.')});
const A={
live:d=>{const r=S.reqs.find(x=>x.id===d.id);if(!r)return;const on=!r.live;T(async()=>{await updateDoc(doc(db,'requests',d.id),{live:on});if(on)await notify(r.student,`${S.me.name} inició la clase. ¡Únete por Meet!`);toast(on?'Clase en vivo iniciada.':'Clase en vivo terminada.')})},
grade:d=>{const u=U(d.id),g=myGrade(d.id);modal(`<h2>⭐ Calificar a ${esc(u.name)}</h2><p class=sub>Tu nota (0 a ${MAXG}). El promedio de las notas de los mentores define quiénes son Alumnos destacados.</p><form data-f=grade data-id=${d.id}><label>Nota</label><select name=value>${Array.from({length:MAXG+1},(_,i)=>MAXG-i).map(n=>`<option ${g&&+g.value===n?'selected':''}>${n}</option>`).join('')}</select><label>Comentario (opcional)</label><textarea name=comment rows=3>${esc(g?.comment||'')}</textarea><div class=row><button class="btn p">Guardar calificación</button><button type=button class=btn data-a=close>Cancelar</button></div></form>`)},
avp:d=>document.querySelectorAll('[data-f=avail] [type=checkbox]').forEach(c=>{c.checked=d.p==='all'||(d.p==='wk'&&!['Sábado','Domingo'].includes(c.name.slice(3)))}),
rf:d=>{S.rf=d.v;render()},
meet:d=>{const r=S.reqs.find(x=>x.id===d.id);if(!r)return;modal(`<h2>🎥 Enlace de Google Meet</h2><p class=sub>Clase con ${esc(U(r.student).name)} · ${fdate(r.date)} ${esc(r.time)}</p><form data-f=meet data-id=${d.id}>${field('link','Enlace (https://meet.google.com/...)',r.meetLink||'','url')}<div class=row><button class="btn p">Guardar enlace</button><a class=btn target=_blank rel=noopener href="https://meet.google.com/new">Crear reunión nueva</a><button type=button class=btn data-a=close>Cancelar</button></div></form>`)},
go:(d)=>{S.view=d.v;S.q='';S.chat=S.chat;$('#sh')?.classList.remove('open');render()},burger:()=>$('#sh').classList.toggle('open'),close,
out:()=>signOut(auth),af:d=>$('#authbox').innerHTML=authForm(d.k),
google:()=>T(async()=>{const r=document.querySelector('[name=role]');S.pending={name:'',role:r?r.value:'student'};await signInWithPopup(auth,new GoogleAuthProvider())}),
pick:d=>$('#ph').value=d.p,hsearch:()=>{S.q=$('#hq').value;S.view='mentors';render()},
mview:d=>modal(mprofile(U(d.id))),
mreq:d=>{const m=U(d.id);modal(`<h2>Solicitar mentoría a ${esc(m.name)}</h2><p class=sub>${esc(m.specialty||'')} · ${esc(availTxt(m))}</p><form data-f=req data-id=${d.id}>${field('date','Fecha propuesta','','date')}${field('time','Hora','','time')}<label>Mensaje</label><textarea name=message rows=3></textarea><div class=row><button class="btn p">Enviar solicitud</button><button type=button class=btn data-a=close>Cancelar</button></div></form>`)},
acc:d=>T(async()=>{const r=S.reqs.find(x=>x.id===d.id);await updateDoc(doc(db,'requests',d.id),{status:'ACEPTADA',sesion:'Confirmada'});await updateDoc(doc(db,'users',S.me.id),{studentsCount:increment(1)});await notify(r.student,`${S.me.name} aceptó tu solicitud de mentoría.`);toast('Solicitud aceptada.')}),
rej:d=>T(async()=>{const r=S.reqs.find(x=>x.id===d.id);await updateDoc(doc(db,'requests',d.id),{status:'RECHAZADA'});await notify(r.student,`${S.me.name} rechazó tu solicitud de mentoría.`);toast('Solicitud rechazada.')}),
ses:d=>T(async()=>{await updateDoc(doc(db,'requests',d.id),{sesion:d.s});toast('Sesión '+d.s.toLowerCase()+'.')}),
open:d=>{S.chat=d.id;render();$('#msgs').scrollTop=1e9},cm:d=>{S.cm+=+d.d;render()},
readall:()=>T(async()=>{for(const n of S.notifs.filter(n=>!n.read))await updateDoc(doc(db,'notifications',n.id),{read:true})}),
reset:()=>T(async()=>{await sendPasswordResetEmail(auth,S.me.email);toast('Te enviamos un correo para restablecer tu contraseña.')}),
uedit:d=>modal(pview(U(d.id))+`<div class=row style="margin-top:14px"><button class="btn p" data-a=aedit data-id=${d.id}>Editar</button><button class=btn data-a=close>Cerrar</button></div>`),aedit:d=>modal(pform(U(d.id),1)),pedit:()=>modal(pform(S.me)),pviewx:d=>modal(mprofile(U(d.id))),msg:d=>{if((S.me.hiddenChats||{})[d.id])updateDoc(doc(db,'users',S.me.id),{['hiddenChats.'+d.id]:deleteField()});S.chat=d.id;S.view='chat';close();render();$('#msgs')&&($('#msgs').scrollTop=1e9)},
cdel:()=>{if(!S.chat||!confirm('¿Eliminar este contacto de tu lista? Reaparecerá si te escribe de nuevo.'))return;const id=S.chat;T(async()=>{await updateDoc(doc(db,'users',S.me.id),{['hiddenChats.'+id]:Date.now()});S.chat=null;render();toast('Contacto eliminado de tu lista.')})},
idel:d=>upd(S.me.id,{[d.k]:(S.me[d.k]||[]).filter((_,i)=>i!==+d.i)}),
aacc:d=>T(async()=>{const r=S.reqs.find(x=>x.id===d.id);await updateDoc(doc(db,'requests',d.id),{status:'ACEPTADA',sesion:'Confirmada'});await updateDoc(doc(db,'users',r.mentor),{studentsCount:increment(1)});await notify(r.student,'Tu solicitud de mentoría fue aceptada.');await notify(r.mentor,'Se aceptó una solicitud de mentoría.');toast('Solicitud aceptada.')}),
arej:d=>T(async()=>{const r=S.reqs.find(x=>x.id===d.id);await updateDoc(doc(db,'requests',d.id),{status:'RECHAZADA'});await notify(r.student,'Tu solicitud de mentoría fue rechazada.');toast('Solicitud rechazada.')}),
uadd:d=>modal(`<h2>Agregar ${d.r==='mentor'?'mentor':'estudiante'}</h2><form data-f=uadd data-r=${d.r}>${field('name','Nombre completo')}${field('email','Correo','','email')}${field('pass','Contraseña temporal (mín. 6)','','password')}${d.r==='mentor'?field('specialty','Especialidad'):field('career','Carrera')}<div class=row><button class="btn p">Crear usuario</button><button type=button class=btn data-a=close>Cancelar</button></div></form>`),
mnew:()=>{const st=S.users.filter(u=>u.role==='student'&&u.active!==false),mt=mentors(),op=l=>l.map(u=>`<option value=${u.id}>${esc(u.name)}</option>`).join('');if(!st.length||!mt.length)return toast('Necesitas al menos un estudiante y un mentor activos.',1);modal(`<h2>Programar mentoría</h2><form data-f=mnew><label>Estudiante</label><select name=student>${op(st)}</select><label>Mentor</label><select name=mentor>${op(mt)}</select>${field('specialty','Especialidad (opcional)')}${field('date','Fecha','','date')}${field('time','Hora','','time')}<label>Estado</label><select name=sesion><option>Confirmada</option><option>Pendiente</option></select><div class=row><button class="btn p">Programar</button><button type=button class=btn data-a=close>Cancelar</button></div></form>`)},
utog:d=>{const u=U(d.id);upd(d.id,{active:u.active===false})},
udel:d=>{if(confirm('¿Eliminar a este usuario? Perderá el acceso a la plataforma.'))T(async()=>{await deleteDoc(doc(db,'users',d.id));toast('Usuario eliminado.')})},
rdel:d=>{if(confirm('¿Eliminar esta solicitud?'))T(()=>deleteDoc(doc(db,'requests',d.id)))}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;if(b.tagName==='A'&&b.getAttribute('href')==='#')e.preventDefault();A[b.dataset.a]?.(b.dataset)});
document.addEventListener('input',e=>{const k=e.target.dataset.in;if(k==='mq'){S.q=e.target.value;$('#list').innerHTML=mlist()}else if(k==='pq'){S.q=e.target.value;$('#list').innerHTML=plist()}else if(k==='sq'){S.q=e.target.value;$('#list').innerHTML=peopleTable(plain(S.view==='mentors'?'mentor':'student'))}});
document.addEventListener('change',e=>{const k=e.target.dataset.in,v=e.target.value,id=e.target.dataset.id;
 if(k==='fd'){S.fd=v;$('#list').innerHTML=mlist()}else if(k==='fe'){S.fe=v;$('#list').innerHTML=mlist()}
 else if(k==='file')e.target.closest('form').querySelector('[name=t]').placeholder='📎 '+(e.target.files[0]?.name||'Escribe un mensaje…');
 else if(k==='ases')T(async()=>{await updateDoc(doc(db,'requests',id),{sesion:v});toast('Estado actualizado.')});
 else if(k==='rate'&&v)T(async()=>{const r=S.reqs.find(x=>x.id===id);await setDoc(doc(db,'ratings',id),{mentor:r.mentor,student:S.me.id,value:+v});toast('¡Gracias por calificar!')})});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,k=f.dataset.f,v=Object.fromEntries(new FormData(f));const em=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,bad=m=>toast(m,1);
 if(k==='login'){if(!v.email||!v.pass)return bad('Debes completar todos los campos.');if(!em.test(v.email))return bad('El correo electrónico no es válido.');T(()=>signInWithEmailAndPassword(auth,v.email,v.pass))}
 else if(k==='reg'){if(!v.name.trim()||!v.email||!v.pass)return bad('Debes completar todos los campos.');if(!em.test(v.email))return bad('El correo electrónico no es válido.');if(v.pass.length<6)return bad('La contraseña debe tener al menos 6 caracteres.');if(v.pass!==v.pass2)return bad('Las contraseñas no coinciden.');S.pending={name:v.name.trim(),role:v.role};T(()=>createUserWithEmailAndPassword(auth,v.email,v.pass))}
 else if(k==='rec'){if(!em.test(v.email))return bad('El correo electrónico no es válido.');T(async()=>{await sendPasswordResetEmail(auth,v.email);toast('Si el correo existe, recibirás un enlace para restablecer tu contraseña.')})}
 else if(k==='msg'){const t=(v.t||'').trim(),fl=v.f;if(!t&&!(fl&&fl.size))return;const ti=f.querySelector('[name=t]');f.reset();ti.placeholder='Escribe un mensaje…';T(async()=>{const file=fl&&fl.size?await pack(fl):null,ts=Date.now(),id=cid(S.me.id,S.chat),mem=[S.me.id,S.chat];await addDoc(collection(db,'messages'),{chatId:id,members:mem,from:S.me.id,text:t,ts,...(file?{file}:{})});await setDoc(doc(db,'chats',id),{members:mem,last:ts,count:increment(1)},{merge:true})})}
 else if(k==='uadd'){if(!v.name.trim()||!v.email||!v.pass)return bad('Debes completar todos los campos.');if(!em.test(v.email))return bad('El correo electrónico no es válido.');if(v.pass.length<6)return bad('La contraseña debe tener al menos 6 caracteres.');
  T(async()=>{const c=await createUserWithEmailAndPassword(secAuth,v.email,v.pass);await signOut(secAuth);await setDoc(doc(db,'users',c.user.uid),{name:v.name.trim(),email:v.email,role:f.dataset.r,specialty:v.specialty||'',career:v.career||'',photo:'',active:true,created:Date.now(),skills:[],availability:[],studentsCount:0});close();toast('Usuario agregado. Compártele su correo y contraseña.')})}
 else if(k==='mnew'){if(!v.date||!v.time)return bad('Debes completar todos los campos.');const m=U(v.mentor);T(async()=>{await addDoc(collection(db,'requests'),{student:v.student,mentor:v.mentor,members:[v.student,v.mentor],specialty:v.specialty||m.specialty||'',date:v.date,time:v.time,message:'Programada por el administrador',status:'ACEPTADA',sesion:v.sesion,created:Date.now()});await notify(v.student,'El administrador programó una mentoría para ti.');await notify(v.mentor,'El administrador programó una mentoría contigo.');close();toast('Mentoría programada.')})}
 else if(k==='iadd'){const n=arr(v.v),kk=f.dataset.k;if(!n.length)return bad('Escribe al menos un elemento.');upd(S.me.id,{[kk]:[...new Set([...(S.me[kk]||[]),...n])]})}
 else if(k==='req'){const m=U(f.dataset.id);if(!v.date||!v.time||!v.message.trim())return bad('Debes completar todos los campos.');if(v.date<new Date().toISOString().slice(0,10))return bad('La fecha no puede estar en el pasado.');
  if(S.reqs.some(r=>r.student===S.me.id&&r.mentor===m.id&&['PENDIENTE','ACEPTADA'].includes(r.status)))return bad('Ya tienes una solicitud activa con este mentor.');
  T(async()=>{await addDoc(collection(db,'requests'),{student:S.me.id,mentor:m.id,members:[S.me.id,m.id],specialty:m.specialty||'',date:v.date,time:v.time,message:v.message.trim(),status:'PENDIENTE',created:Date.now()});await notify(m.id,`${S.me.name} te envió una solicitud de mentoría.`);close();toast('Solicitud enviada correctamente.')})}
 else if(k==='prof'){if(!v.name.trim())return bad('El nombre es obligatorio.');const d={name:v.name.trim(),photo:v.photo||''};
  if('whatsapp'in v){if(v.whatsapp&&!/^\d{8,15}$/.test(v.whatsapp.replace(/\D/g,'')))return bad('El número de WhatsApp no es válido.');d.whatsapp=v.whatsapp.replace(/\D/g,'')}
  if(v.linkedin&&!/^https?:\/\//.test(v.linkedin))v.linkedin='https://'+v.linkedin;['specialty','bio','studies','career','level','city','institution','faculty','linkedin'].forEach(x=>{if(x in v)d[x]=v[x]});['skills','courses','interests','languages'].forEach(x=>{if(x in v)d[x]=arr(v[x])});
  if('experience'in v)d.experience=Math.max(0,+v.experience||0);if('progress'in v)d.progress=Math.min(100,Math.max(0,+v.progress||0));upd(f.dataset.id,d).then(close)}
 else if(k==='avail'){const a=[];for(const d of DAYS)if(v['on_'+d]){if(!v['a_'+d]||!v['b_'+d]||v['a_'+d]>=v['b_'+d])return bad(`${d}: la hora final debe ser posterior a la inicial.`);a.push({d,a:v['a_'+d],b:v['b_'+d]})}upd(S.me.id,{availability:a})}
 else if(k==='specs')upd(S.me.id,{specialty:v.specialty.trim(),skills:arr(v.skills)});
 else if(k==='grade'){const val=+v.value;if(!(val>=0&&val<=MAXG))return bad('La nota debe estar entre 0 y '+MAXG+'.');const sid=f.dataset.id;T(async()=>{await setDoc(doc(db,'grades',S.me.id+'_'+sid),{mentor:S.me.id,student:sid,value:val,comment:(v.comment||'').trim(),updated:Date.now()});await notify(sid,`${S.me.name} te calificó: ${val}/${MAXG}.`);close();toast('Calificación guardada.')})}
 else if(k==='meet'){const l=(v.link||'').trim();if(l&&!/^https:\/\//.test(l))return bad('El enlace debe comenzar con https://');const r=S.reqs.find(x=>x.id===f.dataset.id);T(async()=>{await updateDoc(doc(db,'requests',f.dataset.id),{meetLink:l});if(l&&r)await notify(r.student,`${S.me.name} agregó el enlace de Meet para tu clase.`);close();toast('Enlace guardado.')})}
 else if(k==='wa'){const n=v.whatsapp.replace(/\D/g,'');if(n&&!/^\d{8,15}$/.test(n))return bad('El número de WhatsApp no es válido.');upd(S.me.id,{whatsapp:n})}});
